groups:
  - name: DemoAlerts
    rules:
      - alert: ServicesInstanceDownCritical
        expr: up{job="services"} < 1
        for: 1m
        labels:
          severity: high
        annotations:
          description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.'
          summary: 'Instance {{ $labels.instance }} down'
      - alert: APIInstanceDownCritical
        expr: up{job="api"} < 1
        for: 1m
        labels:
          severity: high
        annotations:
          description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.'
          summary: 'Instance {{ $labels.instance }} down'